# Generated by Django 4.2.4 on 2023-09-04 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_accountant_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='client/jobs')),
                ('deadline', models.DateField()),
                ('accepted_by_account', models.BooleanField(default=False)),
                ('accepted_by_client', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('NS', 'NOT STARTED'), ('OP', 'ON PROCESS'), ('FN', 'FINISHED')], default='NS', max_length=2)),
                ('accountant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.accountant')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profiles.client')),
            ],
        ),
    ]
