# Generated by Django 4.2.5 on 2023-09-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountant',
            name='finish',
            field=models.BooleanField(default=False),
        ),
    ]
