# Generated by Django 4.2.5 on 2023-09-05 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_remove_accountant_finish_job_finish'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='decline',
            field=models.BooleanField(default=False),
        ),
    ]
