# Generated by Django 4.2.5 on 2023-09-07 11:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(20, message="Comment kamida 20 ta belgidan iborat bo'lishi kerak.")]),
        ),
    ]
